### ISSUE TITLE
python_2_unicode_compatible

### ISSUE THREAD

**Issue by zedrood** [geex-arts/django-jet#418]
after install django v3 i got this error. 
```
from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'
```
i see this directory django.utils.encoding , `python_2_unicode_compatible` is not more exists.
and according to Django 3.0 release notes 
```
django.utils.encoding.python_2_unicode_compatible() - Alias of six.python_2_unicode_compatible()
```

**Comment by drewburnett** [comment]
@zedrood Same. Haven't figured out a solution.

**Comment by zedrood** [comment]
solution is use `six.python_2_unicode_compatible()` instead `django.utils.encoding.python_2_unicode_compatible()`  according Django 3.0 release.

**Comment by zedrood** [comment]
> solution is use `six.python_2_unicode_compatible()` instead `django.utils.encoding.python_2_unicode_compatible()` according Django 3.0 release.

**Comment by zedrood** [comment]
six is Utilities for writing code that runs on Python 2 and 3
`pip install six`

**Comment by Pijuli** [comment]
Same here...
180 issues
56 PRs

Is there any community edition being maintained?
R.I.P Jet.
You served well (kind of)

**Comment by huseyinbilgili** [comment]
Is there any solution for this ?

**Comment by yasinkbas** [comment]
> Is there any solution for this ?

-> Just Go error file line 3~5
-> You will see following line 
 **from django.utils.encoding import python_2_unicode_compatible**
Replace this line with 
**from six import python_2_unicode_compatible**

**Comment by juancresc** [comment]
same issue

    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/Users/juan/Documents/manu/dev/profarm_crm/venv/lib/python3.7/site-packages/django/utils/encoding.py)

**Comment by Barukimang** [comment]
Solution of @yasinkbas works, only not for a Docker deployment. Would be great if django 3 fix is approved into new version!

**Comment by Barukimang** [comment]
This version of django-jet works with Django3.0: https://pypi.org/project/django-3-jet/

To install use: `pip install django-3-jet`

**Comment by RamsesMartinez** [comment]
Hi, I created a [Fork](https://pypi.org/project/r-django-jet/
) from this project, which only removes python 2 support to work on python 3, greetings!

**Comment by HoangYell** [comment]
`Six` is used to support code can run on both `python2` and `python3`
Most of us don't use `Python2` anymore. So, we don't need to use `six`. 

**Customize Jet source code** to fix the bug by:
- go to `~/..../virtualenv/your_project/lib/python3.6/site-packages/jet`
  - copy `all jet forlder` to `/your_project`

- in `your_project/jet/models.py`
  - delete all `python_2_unicode_compatible`(import, decorator):

**Done! Issue Resolved!**

**Comment by sushantpatil1214** [comment]
For this Error Use new version of Django Jet 2
Use:-  pip install r-django-jet

https://pypi.org/project/r-django-jet/

**Comment by koyadovic** [comment]
Another solution is also, in the settings.py file of your project, add the following lines above all:
```python
from six import python_2_unicode_compatible
import django.utils.encoding
django.utils.encoding.python_2_unicode_compatible = python_2_unicode_compatible
```
In this way the change comes from your code, it is not necessary to modify installed libraries with the use of pip.

**Comment by cosmy81** [comment]
> Another solution is also, in the settings.py file of your project, add the following lines above all:
> 
> ```python
> from six import python_2_unicode_compatible
> import django.utils.encoding
> django.utils.encoding.python_2_unicode_compatible = python_2_unicode_compatible
> ```
> 
> In this way the change comes from your code, it is not necessary to modify installed libraries with the use of pip.

That's the best solution. It doesn't make you modify the libraries and you can remove it anytime further.  Thank you!!!

**Comment by stopplay** [comment]
> > Is there any solution for this ?
> 
> -> Just Go error file line 3~5
> -> You will see following line
> **from django.utils.encoding import python_2_unicode_compatible**
> Replace this line with
> **from six import python_2_unicode_compatible**

legend

**Comment by micro84** [comment]
pip install bip32utils
